name: attendity
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.10.17
  - pip=23.1.2

  # Face recognition stack (installed via conda)
  - mtcnn=0.1.1

  # Face recognition stack
  - keras=2.15.0
  - tensorflow=2.15.0

  # Database and ORM (installed via conda)
  - sqlalchemy=2.0.41
  - greenlet=2.0.2

  # System dependencies
  - cmake=4.0.2
  - libboost=1.81.0
  - libblas=3.9.0
  - liblapack=3.9.0

  # Core packages
  - numpy=1.24.3
  - pandas=2.2.3
  - bcrypt=4.3.0
  - python-dotenv=1.1.0
  - typing-extensions=4.6.0

  # Streamlit stack
  - streamlit=1.45.1
  - streamlit-extras=0.7.1
  - watchdog=2.1.6

  # Computer vision (installed via conda where possible)
  - opencv=4.11.0
  - dlib=19.24.0

  # Pip packages
  - pip:
      - face_recognition==1.3.0
      - git+https://github.com/ipazc/mtcnn.git
      - keras-vggface==0.6
      - tensorflow-cpu==2.15.0
      - keras==2.15.0
      - protobuf==5.27.3
