name: attendity
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.17
  - pip
  - pip:
      - streamlit==1.45.1
      - streamlit-extras==0.7.1
      - bcrypt==4.3.0
      - dlib==19.24.0
      - numpy==2.1.3
      - opencv-python==4.11.0.86
      - python-dotenv==1.1.0
      - sqlalchemy==2.0.41
      - face_recognition==1.3.0
      - pandas==2.2.3
      - mtcnn==1.0.0
